# Generated by Django 2.1.2 on 2018-10-15 19:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0004_auto_20181015_1944'),
    ]

    operations = [
        migrations.CreateModel(
            name='Follow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mainApp.Events')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mainApp.UserBasic')),
            ],
        ),
    ]
