# Generated by Django 2.1.2 on 2018-10-16 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0006_auto_20181016_1606'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserBasic',
        ),
    ]
