# Generated by Django 2.1.2 on 2018-10-18 17:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0007_delete_userbasic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='follow',
            name='event_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainApp.Events'),
        ),
    ]
